name: Build & Test Microservices

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Formatting text
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Set Up golang
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: Set Up linter
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: auth-service
          version: latest
