name: Publish Docker Image

on:
  pull:
  push:
    branches:
      - main

jobs:
  validate:
    name: Formatting text
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses:  actions/checkout@v4

      - name: Get golang
        uses:  actions/setup-go@v5
          with:   
            go-version:  "1.25"

      - name: Formatting
        run: go fmt ./...
